// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbegedxfpdjsduubgjmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiZWdlZHhmcGRqc2R1dWJnam1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MzM4MzQsImV4cCI6MjA2MzQwOTgzNH0.HsBw34pIjW5Exp9B_haiywoYReZJe6ioTRh8PEqsi90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});